### ISSUE TITLE
Stereo

### ISSUE THREAD

**Issue by Baggypants** [devcurmudgeon/alo#5]
Stereo inputs and outputs would be nice!

**Comment by devcurmudgeon** [comment]
@Baggypants master now should work in stereo. Please let me know if you get a chance to test it

**Comment by Baggypants** [comment]
Works fine on my zynthian. I did a stereo test here: https://discourse.zynthian.org/t/any-decent-looper-in-future-plans/3577/14?u=baggypants

**Comment by devcurmudgeon** [comment]
Excellent, I'll close this then. If you have more suggetions please let me know
