### ISSUE TITLE
PiSound Modep Support

### ISSUE THREAD

**Issue by ElijahLynn** [devcurmudgeon/alo#6]
Hi,

I am trying to build and get the Alo looper working in MODEP over here > https://community.blokas.io/t/alo-looper-plugin-build/1941/3. I got it built and showing in the UI but not able to trigger it with an audio input threshold no matter what I set it to. 

Do you have any suggestions on what I would need to get it working under MODEP on the PiSound?

I am super interested to get this working as the Sooper Looper has clicks when the loop closes/starts and it is unusable for me right now.

**Comment by ElijahLynn** [comment]
I just ordered the Mod Duo and Footswitch bundle > https://shop.moddevices.com/product/mod-duo-bundle/?v=a067a59197f9 so I personally will be able to just use it on Mod. But still would love to get this working on Pisound as I may give it to a friend of mine.

**Comment by devcurmudgeon** [comment]
Hi @ElijahLynn I've commented on the issue at blokas.io - since others have previously got it working I'm hoping there shouldn't be a problem once you've got the MODEP equivalent of global BPM running. Please let me know if there's anything I can do to help

**Comment by ElijahLynn** [comment]
> Hi @ElijahLynn I've commented on the issue at blokas.io - since others have previously got it working I'm hoping there shouldn't be a problem once you've got the MODEP equivalent of global BPM running. Please let me know if there's anything I can do to help

Thanks a bunch, I replied there.
