### ISSUE TITLE
Prefixing version number in release titles?

### ISSUE THREAD

**Issue by mxmilkiib** [devcurmudgeon/alo#7]
Hello! I'd like to ad ALO to https://libreav.org/updates but it's not possible to parse the version from the [feed](https://github.com/devcurmudgeon/alo/releases.atom) because the version number isn't in the title.

Could it be possible to edit the existing release titles so they have the version number at the start or end? Then I can regex the rest of the title text away.

**Comment by devcurmudgeon** [comment]
I've updated the titles - is that what you need?

**Comment by mxmilkiib** [comment]
Yes, thanks, that's great!
